USE [D:\STEP ACEDAMY\C#\MYWPFPROJECTSDBOPRODUCT\SERVER\DAO\SKYPEDATABASE.MDF]
GO

/****** Object:  StoredProcedure [dbo].[SP_Contact_SEL_byUserID]    Script Date: 09.08.2015 23:37:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_Contact_SEL_byUserID]
	@UserID int
AS
BEGIN TRY
	SELECT UserID, Email, [Login], [ImageName]
	FROM [dbo].[User]
	WHERE UserID = @UserID
	RETURN 1;
END TRY
BEGIN CATCH
	RETURN 0;
END CATCH


GO

