//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeServer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DIMA-PC;Initial Catalog=Airport;Integrated Security=True")]
        public string AirportConnectionString {
            get {
                return ((string)(this["AirportConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=|DataDirectory|\\DAO\\SkypeDatabase.md" +
            "f;Integrated Security=True;Connect Timeout=30")]
        public string SkypeDatabaseConnectionString {
            get {
                return ((string)(this["SkypeDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DIMA-PC;Initial Catalog=\"D:\\STEP ACEDAMY\\C#\\MYWPFPROJECTSDBOPRODUCT\\S" +
            "ERVER\\DAO\\SKYPEDATABASE.MDF\";Integrated Security=True")]
        public string D__STEP_ACEDAMY_C__MYWPFPROJECTSDBOPRODUCT_SERVER_DAO_SKYPEDATABASE_MDFConnectionString {
            get {
                return ((string)(this["D__STEP_ACEDAMY_C__MYWPFPROJECTSDBOPRODUCT_SERVER_DAO_SKYPEDATABASE_MDFConnection" +
                    "String"]));
            }
        }
    }
}
